version: "3.8"

services:
  web:
    build: .
    image: tangeleski/gaming-app:latest
    container_name: gaming-app
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: postgres:latest
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped