# CONFIGMAP AND SECRET

apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: gaming-app-namespace
data:
  POSTGRES_DATABASE: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_HOST: "postgres-service.gaming-app-namespace.svc.cluster.local"
  POSTGRES_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  namespace: gaming-app-namespace
type: Opaque
data:
  POSTGRES_PASSWORD: YWRtaW4=
#  ------------ Deployment -------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaming-app-deployment
  namespace: gaming-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gaming-app
  template:
    metadata:
      labels:
        app: gaming-app
    spec:
      initContainers:
        - name: init-static-files
          image: tangeleski/gaming-app:latest
          command: [ '/bin/sh', "-c" ]  # Load shell to copy static files from docker image
          args:
            - cp -r /code/app/static/* /mnt/static-files/;
          volumeMounts:
            - mountPath: /mnt/static-files
              name: static-files
      containers:
        - name: gaming-app
          image: tangeleski/gaming-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: fastapi-config
            - secretRef:
                name: fastapi-secret
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: static-files-pvc